theme = "kanarus"

[editor]
shell = ["zsh", "~/.config/helix/shell.sh"]
mouse = false
default-yank-register = "+" # use system clipboard by default
continue-comments = false

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
