theme = "kanarus"

[editor]
# shell = ['zsh', '-c', 'exec zsh -ic "$1 && exit 0"', '--']
shell = ['zsh', '-ic', 'eval "$1"', '--']
mouse = false
default-yank-register = "+" # use system clipboard by default
continue-comments = false

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
