theme = "meliora"

[editor]
shell = ['zsh', '-ic', 'eval "$1"', '--']
mouse = false
scroll-lines = 0
scrolloff = 0
trim-trailing-whitespace = true
continue-comments = false

[editor.file-picker]
git-ignore = false
git-global = false

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.auto-save]
after-delay = { enable = true, timeout = 500 }
